#!/usr/bin/env node
// BloomMap render harness — headless-Chrome render of the live D3 page,
// then extract the generated <svg> and rasterise to PNG via rsvg-convert.
//
// Usage:
//   node render.mjs [index.html] [out.svg] [out.png] [width]
//
// The SVG is generated by D3 at runtime, so we run the page in real Chrome,
// wait for the Voronoi layout to settle, then serialise the resulting <svg>.
// Drives Chrome over the DevTools Protocol via Node 23's built-in WebSocket.

import { spawn, spawnSync } from "node:child_process";
import { writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir, platform } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { existsSync } from "node:fs";

// Find a headless-capable Chrome/Chromium. Set CHROME_PATH to override.
function findChrome() {
  if (process.env.CHROME_PATH) return process.env.CHROME_PATH;
  const candidates = {
    darwin: [
      "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
      "/Applications/Chromium.app/Contents/MacOS/Chromium",
    ],
    linux: [
      "/usr/bin/google-chrome", "/usr/bin/google-chrome-stable",
      "/usr/bin/chromium", "/usr/bin/chromium-browser", "/snap/bin/chromium",
    ],
    win32: [
      "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
      "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
    ],
  }[platform()] || [];
  const found = candidates.find(existsSync);
  if (!found) {
    console.error(
      "No Chrome/Chromium found. Install Google Chrome or Chromium, or set " +
      "CHROME_PATH to the executable. Tried:\n  " + candidates.join("\n  ")
    );
    process.exit(1);
  }
  return found;
}

const CHROME = findChrome();

const htmlPath = resolve(process.argv[2] || "index.html");
const outSvg = resolve(process.argv[3] || "out.svg");
const outPng = resolve(process.argv[4] || "out.png");
const width = parseInt(process.argv[5] || "1400", 10);
const url = pathToFileURL(htmlPath).href;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const userDataDir = mkdtempSync(join(tmpdir(), "bloommap-chrome-"));
const port = 9222;
const chrome = spawn(
  CHROME,
  [
    "--headless=new",
    "--disable-gpu",
    "--no-sandbox",
    "--hide-scrollbars",
    "--allow-file-access-from-files", // d3.json() fetches sibling JSON over file://
    "--disable-web-security",
    `--remote-debugging-port=${port}`,
    `--user-data-dir=${userDataDir}`,
    "--window-size=2400,2400",
    "about:blank",
  ],
  { stdio: ["ignore", "ignore", "ignore"] },
);

async function getJSON(u) {
  const res = await fetch(u);
  return res.json();
}

// Single dispatcher over one WebSocket: id->resolver map + event sink.
function makeClient(ws) {
  let nextId = 0;
  const pending = new Map();
  const consoleMsgs = [];
  ws.addEventListener("message", (e) => {
    const m = JSON.parse(e.data.toString());
    if (m.id !== undefined && pending.has(m.id)) {
      const { resolve, reject } = pending.get(m.id);
      pending.delete(m.id);
      if (m.error) reject(new Error(JSON.stringify(m.error)));
      else resolve(m.result);
    } else if (m.method === "Runtime.consoleAPICalled") {
      const txt = (m.params.args || [])
        .map((a) => a.value ?? a.description ?? "")
        .join(" ");
      consoleMsgs.push(`[${m.params.type}] ${txt}`);
    } else if (m.method === "Runtime.exceptionThrown") {
      const d = m.params.exceptionDetails;
      consoleMsgs.push(
        `[exception] ${d.exception?.description || d.text || "unknown"}`,
      );
    }
  });
  const send = (method, params = {}) =>
    new Promise((resolve, reject) => {
      const id = ++nextId;
      pending.set(id, { resolve, reject });
      ws.send(JSON.stringify({ id, method, params }));
    });
  return { send, consoleMsgs };
}

// Build a standalone, self-contained HTML page wrapping the rendered SVG with a
// CSS/JS tooltip layer (WP-E4). Event delegation: ONE listener set on the SVG
// root walks up from event.target to the nearest ancestor carrying data-title
// (petal wedges and petal-title groups are tagged by visualization.js), so the
// per-element cost is just the data-title string — cheap at ~40-200 petals. The
// tooltip follows the cursor on hover, appears on keyboard focus, and toggles on
// touch. Native <title> children stay in the SVG as the no-JS / a11y fallback.
function buildHoverHtml(svgMarkup) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>UltraDim BloomMap — hover for cluster titles</title>
<style>
  :root { color-scheme: light; }
  body { margin: 0; background: #fafafa; font: 14px/1.4 system-ui, -apple-system, sans-serif; color: #222; }
  #bloom { display: block; max-width: 100%; height: auto; margin: 0 auto; }
  #bloom svg { max-width: 100%; height: auto; }
  /* A tagged petal is interactive: cursor + a faint lift on hover/focus. */
  #bloom [data-title] { cursor: pointer; }
  #bloom [data-title]:hover, #bloom [data-title]:focus { opacity: 0.82; outline: none; }
  #tt {
    position: fixed; z-index: 10; pointer-events: auto;
    background: rgba(20,20,25,.95); color: #fff; padding: 7px 11px;
    border-radius: 6px; font-size: 13px; line-height: 1.35; max-width: 360px;
    box-shadow: 0 2px 12px rgba(0,0,0,.32); opacity: 0; transition: opacity .08s;
    transform: translate(-50%, calc(-100% - 12px)); white-space: pre-line;
  }
  /* When the tooltip is hidden it must not intercept the cursor. */
  #tt:not(.on) { pointer-events: none; }
  #tt a { color: #7cc4ff; text-decoration: underline; }
  #tt a:hover, #tt a:focus { color: #aad8ff; }
  #hint { text-align: center; color: #888; padding: 10px; font-size: 12px; }
</style>
</head>
<body>
<div id="bloom">
${svgMarkup}
</div>
<div id="hint">Hover, focus, or tap a cell to reveal the movie title; click it to open IMDb.</div>
<div id="tt" role="status" aria-live="polite"></div>
<script>
(function () {
  var tt = document.getElementById("tt");
  var root = document.querySelector("#bloom svg");
  if (!root) return;
  // Walk up to the nearest ancestor carrying data-title (within the svg).
  function titledAncestor(node) {
    while (node && node !== root) {
      if (node.getAttribute && node.getAttribute("data-title")) return node;
      node = node.parentNode;
    }
    return null;
  }
  // Render the tooltip body for one titled element. A cell that carries a
  // data-href (an IMDb URL) renders its title as a clickable anchor (opens in a
  // new tab); anything else (petal-level hovers, cells without an IMDb id) shows
  // the plain title text. The anchor's text IS the title, so tt.textContent still
  // equals data-title either way.
  function render(el) {
    var text = el.getAttribute("data-title") || "";
    var href = el.getAttribute("data-href") || "";
    while (tt.firstChild) tt.removeChild(tt.firstChild);
    if (href) {
      var a = document.createElement("a");
      a.href = href;
      a.target = "_blank";
      a.rel = "noopener noreferrer";
      a.textContent = text;
      tt.appendChild(a);
    } else {
      tt.textContent = text;
    }
  }
  var hideTimer = null;
  function cancelHide() { if (hideTimer) { clearTimeout(hideTimer); hideTimer = null; } }
  function show(el, x, y) {
    cancelHide();
    render(el);
    tt.style.left = x + "px";
    tt.style.top = y + "px";
    tt.classList.add("on");
  }
  function hideNow() { cancelHide(); tt.classList.remove("on"); }
  // Delay hide so the cursor can travel from the cell onto the tooltip to click
  // the IMDb link (hover-intent bridge); moving onto the tooltip cancels it.
  function hideSoon() { cancelHide(); hideTimer = setTimeout(function () { tt.classList.remove("on"); }, 220); }
  root.addEventListener("mousemove", function (e) {
    var el = titledAncestor(e.target);
    if (el) show(el, e.clientX, e.clientY);
    else hideSoon();
  });
  root.addEventListener("mouseleave", hideSoon);
  // Keep the tooltip open while the pointer is over it (so its link is clickable).
  tt.addEventListener("mouseenter", cancelHide);
  tt.addEventListener("mouseleave", hideNow);
  // Keyboard: tabbable cells raise focus events (make them focusable on the fly).
  root.querySelectorAll("[data-title]").forEach(function (el) {
    el.setAttribute("tabindex", "0");
    el.addEventListener("focus", function () {
      var r = el.getBoundingClientRect();
      show(el, r.left + r.width / 2, r.top + r.height / 2);
    });
    el.addEventListener("blur", hideSoon);
  });
  // Touch: tap a cell to show, tap elsewhere to hide.
  root.addEventListener("touchstart", function (e) {
    var el = titledAncestor(e.target);
    if (el) { var t = e.touches[0]; show(el, t.clientX, t.clientY); }
  }, { passive: true });
  document.addEventListener("touchstart", function (e) {
    if (!titledAncestor(e.target) && e.target !== tt && !tt.contains(e.target)) hideNow();
  }, { passive: true });
})();
</script>
</body>
</html>
`;
}

async function main() {
  let target = null;
  for (let i = 0; i < 80; i++) {
    try {
      const list = await getJSON(`http://127.0.0.1:${port}/json`);
      target = list.find((t) => t.type === "page");
      if (target) break;
    } catch {}
    await sleep(250);
  }
  if (!target) throw new Error("Chrome devtools endpoint not reachable");

  const ws = new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((r, j) => {
    ws.onopen = r;
    ws.onerror = j;
  });
  const { send, consoleMsgs } = makeClient(ws);

  await send("Page.enable");
  await send("Runtime.enable");

  // Inject taste overrides from env (e.g. BLOOMMAP_TINT) BEFORE the page's own
  // scripts run, so visualization.js picks them up. Lets us step the colour
  // tint without editing the file.
  const overrides = {};
  if (process.env.BLOOMMAP_TINT !== undefined)
    overrides.BLOOMMAP_TINT = parseFloat(process.env.BLOOMMAP_TINT);
  // Number of nearest-centroid titles printed on each leaf sector (petal label).
  // 1 = the single nearest movie (the shipped look); the multi-title variant was
  // retired as too crowded, so posters render at the default 1.
  if (process.env.BLOOMMAP_LEAF_LABELS !== undefined)
    overrides.BLOOMMAP_LEAF_LABELS = parseInt(process.env.BLOOMMAP_LEAF_LABELS, 10);
  // Hover mode (--hover html|off). "html" makes visualization.js tag petals with
  // data-title + a native <title> fallback, and makes this harness ALSO emit a
  // standalone self-contained HTML artefact with a CSS/JS tooltip layer. "off"
  // (default) adds nothing — the SVG is byte-identical to a no-hover render.
  const hoverMode = (process.env.BLOOMMAP_HOVER || "off").toLowerCase();
  if (hoverMode === "html") overrides.BLOOMMAP_HOVER = "html";
  else if (hoverMode === "pdf") {
    // PDF hover is Acrobat-only and dropped by the rsvg SVG->PDF path (see
    // docs/BloomMap_Hover_Investigation.md). Not implemented; fall back to off.
    console.error(
      "WARNING: --hover pdf is not implemented (Acrobat-only, dropped by rsvg SVG->PDF); rendering with hover off.",
    );
  } else if (hoverMode !== "off") {
    throw new Error(`--hover must be html|pdf|off, got '${hoverMode}'`);
  }
  if (Object.keys(overrides).length) {
    const src = Object.entries(overrides)
      .map(([k, v]) => `window[${JSON.stringify(k)}]=${JSON.stringify(v)};`)
      .join("");
    await send("Page.addScriptToEvaluateOnNewDocument", { source: src });
  }

  await send("Page.navigate", { url });
  await sleep(4000); // let D3 + Voronoi layout settle

  // Readiness = the svg has many descendant <path> elements (cells drawn).
  // Voronoi treemap for ~66 clusters can take several seconds; poll on a
  // stable descendant count (two equal reads in a row = settled).
  let svg = "";
  let lastPaths = -1;
  let stable = 0;
  for (let i = 0; i < 60; i++) {
    const r = await send("Runtime.evaluate", {
      expression: `(() => {
        const s = document.getElementById('visualization');
        if (!s) return JSON.stringify({paths:-1});
        const paths = s.querySelectorAll('path').length;
        const texts = s.querySelectorAll('text').length;
        return JSON.stringify({paths, texts, svg: paths>50 ? s.outerHTML : ''});
      })()`,
      returnByValue: true,
    });
    const parsed = JSON.parse(r.result.value);
    if (parsed.paths === lastPaths && parsed.paths > 50) {
      stable++;
      if (stable >= 2) {
        svg = parsed.svg;
        console.error(`settled: ${parsed.paths} paths, ${parsed.texts} texts`);
        break;
      }
    } else {
      stable = 0;
    }
    lastPaths = parsed.paths;
    await sleep(500);
  }

  if (consoleMsgs.length) {
    console.error("--- page console ---");
    for (const m of consoleMsgs.slice(0, 30)) console.error(m);
    console.error("--------------------");
  }
  if (!svg)
    throw new Error(`SVG never populated (last path count=${lastPaths})`);

  if (!svg.includes("xmlns=")) {
    svg = svg.replace(
      "<svg",
      '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"',
    );
  }
  svg = svg.replace(
    /<svg([^>]*)>/,
    '<svg$1><rect width="100%" height="100%" fill="white"/>',
  );
  writeFileSync(outSvg, svg);

  // Standalone HTML hover artefact (--hover html). Self-contained: the SVG is
  // inlined and the tooltip CSS/JS is inline too (no external files, opens over
  // file://). One delegated listener on the SVG root reads data-title off the
  // hovered/focused/tapped element; native <title> children (added by
  // visualization.js) remain the no-JS / screen-reader fallback. Output path =
  // outSvg with .html (or BLOOMMAP_HOVER_HTML if set).
  if (overrides.BLOOMMAP_HOVER === "html") {
    const outHtml =
      process.env.BLOOMMAP_HOVER_HTML || outSvg.replace(/\.svg$/i, "") + ".html";
    writeFileSync(outHtml, buildHoverHtml(svg));
    console.error(`hover html: ${outHtml}`);
  }

  const r2 = spawnSync("rsvg-convert", ["-w", String(width), "-o", outPng, outSvg], {
    stdio: "inherit",
  });
  if (r2.status !== 0) throw new Error("rsvg-convert failed");
  ws.close();
}

main()
  .then(() => {
    chrome.kill("SIGKILL");
    // Chrome may still hold the profile dir for a moment after SIGKILL; retry
    // cleanup a few times so a benign ENOTEMPTY never fails the render.
    for (let i = 0; i < 10; i++) {
      try {
        rmSync(userDataDir, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
        break;
      } catch (_) {
        const until = Date.now() + 150;
        while (Date.now() < until) {} // brief spin; no async in this exit path
      }
    }
    console.log(`OK: ${outSvg} + ${outPng}`);
    process.exit(0);
  })
  .catch((e) => {
    chrome.kill("SIGKILL");
    // Chrome may still hold the profile dir for a moment after SIGKILL; retry
    // cleanup a few times so a benign ENOTEMPTY never fails the render.
    for (let i = 0; i < 10; i++) {
      try {
        rmSync(userDataDir, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
        break;
      } catch (_) {
        const until = Date.now() + 150;
        while (Date.now() < until) {} // brief spin; no async in this exit path
      }
    }
    console.error("RENDER ERROR:", e.message);
    process.exit(1);
  });
